export default {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_CART: 'FETCH_CART',
    FETCH_WISHLIST: 'FETCH_WISHLIST',
    HANDLE_CHANGE: 'HANDLE_CHANGE',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    UPDATE_CART_QUANTITY: 'UPDATE_CART_QUANTITY',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
    FILTER_WITH_CATEGORY: 'FILTER_WITH_CATEGORY',
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL'
}